#!/usr/bin/env python3
#-*- coding:utf-8 -*-

import sys, json

src = {
    "ret":1,
    "apiver":9,
    "name":"pyCompact",
    "author":"dixyes",
    "description":"python3 插件",
    "event":[
        {
            "id":1,
            "type":21,
            "name":"私聊消息处理",
            "function":"_eventPrivateMsg",
            "priority":30000
        },
        {
            "id":2,
            "type":2,
            "name":"群消息处理",
            "function":"_eventGroupMsg",
            "priority":30000
        },
        {
            "id":3,
            "type":4,
            "name":"讨论组消息处理",
            "function":"_eventDiscussMsg",
            "priority":30000
        },
        {
            "id":5,
            "type":101,
            "name":"群管理变动事件处理",
            "function":"_eventSystem_GroupAdmin",
            "priority":30000
        },
        {
            "id":6,
            "type":102,
            "name":"群成员减少事件处理",
            "function":"_eventSystem_GroupMemberDecrease",
            "priority":30000
        },
        {
            "id":7,
            "type":103,
            "name":"群成员增加事件处理",
            "function":"_eventSystem_GroupMemberIncrease",
            "priority":30000
        },
        {
            "id":10,
            "type":201,
            "name":"好友已添加事件处理",
            "function":"_eventFriend_Add",
            "priority":30000
        },
        {
            "id":8,
            "type":301,
            "name":"好友添加请求处理",
            "function":"_eventRequest_AddFriend",
            "priority":30000
        },
        {
            "id":9,
            "type":302,
            "name":"群添加请求处理",
            "function":"_eventRequest_AddGroup",
            "priority":30000
        },
        {
            "id":1001,
            "type":1001,
            "name":"酷Q启动事件",
            "priority":30000,
            "function":"_eventStartup"
        },
        {
            "id":1002,
            "type":1002,
            "name":"酷Q关闭事件",
            "priority":30000,
            "function":"_eventExit"
        },
        {
            "id":1003,
            "type":1003,
            "name":"应用已被启用",
            "priority":30000,
            "function":"_eventEnable"
        },
        {
            "id":1004,
            "type":1004,
            "name":"应用将被停用",
            "priority":30000,
            "function":"_eventDisable"
        }
    ],
    "menu":[
        {
            "name":"选择加载DLL(仅未成功加载DLL时可用)",
            "function":"_menuLoadModule"
        },
        {
            "name":"开放源代码许可",
            "function":"_menuShowLicense"
        }
    ],
    "status":[],
    "auth":[30,101,103,106,110,120,121,122,123,124,125,126,127,128,130,131,140,150,151,180]
}
srcDbg = {
    "ret":1,
    "apiver":9,
    "name":"pyCompactD",
    "author":"dixyes",
    "description":"python3 插件(使用python3x_d加载)",
    "event":[
        {
            "id":1,
            "type":21,
            "name":"私聊消息处理",
            "function":"_eventPrivateMsg",
            "priority":30000
        },
        {
            "id":2,
            "type":2,
            "name":"群消息处理",
            "function":"_eventGroupMsg",
            "priority":30000
        },
        {
            "id":3,
            "type":4,
            "name":"讨论组消息处理",
            "function":"_eventDiscussMsg",
            "priority":30000
        },
        {
            "id":5,
            "type":101,
            "name":"群管理变动事件处理",
            "function":"_eventSystem_GroupAdmin",
            "priority":30000
        },
        {
            "id":6,
            "type":102,
            "name":"群成员减少事件处理",
            "function":"_eventSystem_GroupMemberDecrease",
            "priority":30000
        },
        {
            "id":7,
            "type":103,
            "name":"群成员增加事件处理",
            "function":"_eventSystem_GroupMemberIncrease",
            "priority":30000
        },
        {
            "id":10,
            "type":201,
            "name":"好友已添加事件处理",
            "function":"_eventFriend_Add",
            "priority":30000
        },
        {
            "id":8,
            "type":301,
            "name":"好友添加请求处理",
            "function":"_eventRequest_AddFriend",
            "priority":30000
        },
        {
            "id":9,
            "type":302,
            "name":"群添加请求处理",
            "function":"_eventRequest_AddGroup",
            "priority":30000
        },
        {
            "id":1001,
            "type":1001,
            "name":"酷Q启动事件",
            "priority":30000,
            "function":"_eventStartup"
        },
        {
            "id":1002,
            "type":1002,
            "name":"酷Q关闭事件",
            "priority":30000,
            "function":"_eventExit"
        },
        {
            "id":1003,
            "type":1003,
            "name":"应用已被启用",
            "priority":30000,
            "function":"_eventEnable"
        },
        {
            "id":1004,
            "type":1004,
            "name":"应用将被停用",
            "priority":30000,
            "function":"_eventDisable"
        }
    ],
    "menu":[
        {
            "name":"重载Python脚本",
            "function":"_menuReloadScript"
        },
        {
            "name":"选择加载DLL(不稳定,将会重载脚本)",
            "function":"_menuLoadModule"
        },
        {
            "name":"开放源代码许可",
            "function":"_menuShowLicense"
        }
    ],
    "status":[],
    "auth":[30,101,103,106,110,120,121,122,123,124,125,126,127,128,130,131,140,150,151,180]
}

if __name__ == "__main__":
    print("building json file %s for %s build" % (sys.argv[1],sys.argv[2]) )
    toParse = srcDbg
    if len(sys.argv) > 2:
        if "release" == sys.argv[2].lower():
            toParse = src
    toParse["version"] = "0.0.2", # todo: from env
    toParse["version_id"] = 3, #    ^
    with open(sys.argv[1],"w",encoding="gb18030") as f:
        f.write(json.dumps(toParse, indent = 2, ensure_ascii=False))
    #print(json.dumps(toParse, indent = 2, ensure_ascii=False))
